### PR TITLE
Migrate Travis CI to Github Actions

### LINKED ISSUE #50: Migrate Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by kamils-iRonin**
Fixes #50

### CODE REVIEW

**Comment by timogoebel** [comment]
The tests don't seem to run on this PR, do we need to whitelist them or something?

**Comment by kamils-iRonin** [comment]
@timogoebel workflow was started on a forked repo https://github.com/kamils-iRonin/foreman_git_templates/actions/runs/34998728, I think that when it is merged, workflow will also be started on this repo
I wonder if we want to use [rubocop-linter-action](https://github.com/andrewmcodes/rubocop-linter-action), it needs to set `GITHUB_TOKEN` secret in the repository settings

**Comment by kamils-iRonin** [comment]
@timogoebel I think it's ready to be merged. You can see the tests results here
https://github.com/kamils-iRonin/foreman_git_templates/actions/runs/43550660

**Comment by timogoebel** [comment]
Thanks, @kamils-iRonin!

**Pull request merged**
